# Generated by Django 2.2.6 on 2019-10-21 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('abstract', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=1024)),
                ('date', models.DateField()),
                ('time_to_read', models.IntegerField()),
                ('image', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trends.Article')),
            ],
        ),
    ]
