version: '3'

services:
  db: #is the database, named localhost to allow usage outside of containers
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'trends_database'
       MYSQL_ROOT_PASSWORD: 'pass'